title: Siwei Li's Homepage
page-top-title: Siwei Li
top-section-bg-text: "啊啊啊啊啊宝宝你是一个哈基米！\n哈！😼"
home-subtitle: Siwei Li&ensp;|&ensp;李思玮&ensp;|&ensp;INTJ-A&ensp;|&ensp;天蝎座
copyright-text: '&copy; Siwei Li 2025-2026. All Rights Reserved.'
github-link: https://github.com/lixiaoshuai1113
license-link: https://github.com/lixiaoshuai1113/lixiaoshuai1113.github.io/blob/main/LICENSE
